# GitHub Actions - CI for Go with just builders and tests.
# https://github.com/x448/float16/blob/master/.github/workflows/ci.yml 
# Use cover.yml for coverage and safer-golangci-lint.yml for linting.
name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

# Revoke default permissions.
permissions: {}
  
jobs:
  # Test on various OS and go versions.
  tests:
    name: test ${{matrix.os}} go-${{ matrix.go-version }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-version: [1.17, 1.18, 1.19]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build project
      run: go build ./...

    - name: Run tests
      run: |
        go version
        go test -short -race -v ./...
